- name: Copy file cấu hình Nginx tĩnh
  ansible.builtin.copy:
    src: ./nginx.conf # Đường dẫn file trên máy bạn
    dest: /etc/nginx/nginx.conf # Đường dẫn trên Server
    owner: root # Chủ sở hữu
    group: root # Nhóm
    mode: "0644" # Phân quyền (r--r--r--)
    backup: yes # Tự động tạo bản backup nếu file cũ đã tồn tại
